### ISSUE TITLE
Question - what file formats does this support

### ISSUE THREAD

**Issue by kubaraczkowski** [drualcman/webserver-printing#1]
Hey,
Awesome idea. I'd like to make it into a very simple frontend that lets a user upload a document and it gets printed on a home printer. The reason is that the school laptops my kids have don't allow adding printers... 

What formats do you accept, will there be any format conversion done? PDF? PS? DOCX? JPEG?

Thanks!

**Comment by drualcman** [comment]
This tool print any kind of document because you must be send in a bytes formated for the princter you will use.

Remind about this tool it's good to use if you can use localhost. The tool it's running in the local machine. Also can be used over a LAN.

I created other versino using WEBSOCKETS, but this is a commercial licence.
